# Generated by Django 4.2.7 on 2024-07-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="division",
            new_name="split_method",
        ),
    ]
