# Generated by Django 4.2.7 on 2024-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_rename_division_expense_split_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="amount",
        ),
        migrations.AddField(
            model_name="expense",
            name="detail",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
    ]
