# Generated by Django 4.2.7 on 2024-07-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_remove_expense_amount_expense_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="detail",
            new_name="details",
        ),
    ]
